project:
  type: website

website:
  title: "KnowledgeCentRe"
  
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - text: "SAS to R"
        href: sas-to-r/index.qmd
      - text: "R Hub"
        menu:
          - href: r-hub/beginner.qmd
            text: "R for Beginners"
          - href: r-hub/clinical.qmd
            text: "Clinical Trials Analysis"
          - href: r-hub/advanced.qmd
            text: "R for Advanced Users"
          - href: r-hub/resources.qmd
            text: "Resources"
      - text: "Shinyverse"
        menu:
          - href: shinyverse/basics.qmd
            text: "Getting Started"
          - href: shinyverse/beyond-basics.qmd
            text: "Beyond Basics"
          - href: shinyverse/clinical-shiny.qmd
            text: "Clinical Shiny"
          - href: shinyverse/deployment.qmd
            text: "Deploying Shiny Apps"
          - href: shinyverse/resources.qmd
            text: "Resources"
      - href: blog/index.qmd
        text: Blog
    right: 
      - href: sme-rescue/index.qmd
        text: "SME to the Rescue"
        icon: life-preserver
  
  sidebar:
    - title: "SAS to R Migration"
      id: "sas-to-r"
      contents:
        - sas-to-r/index.qmd
        - sas-to-r/01-introduction.qmd
        - sas-to-r/02-ecosystem.qmd
        - sas-to-r/03-data-structures.qmd
        - sas-to-r/04-data-io.qmd
        - sas-to-r/05-data-wrangling.qmd
        - sas-to-r/06-merging-joining.qmd
        - sas-to-r/07-advanced-programming.qmd
        - sas-to-r/08-reporting.qmd
        - sas-to-r/09-clinical-workflows.qmd
        - sas-to-r/10-package-development.qmd

  
  page-footer:
    background: primary
    left: "© 2024 KnowledgeCentRe | Syneos Health"
    right: 
      - href: mailto:harsh.verma@syneoshealth.com
        text: "Contact Creator"
        
format:
  html:
    theme: 
      light: cosmo
      dark: superhero # 'darkly' or 'superhero' are great dark themes
    css: styles.css
    toc: true

editor: visual

